title: Harry Kim  # your name (or website title) here
logo: 'image/avatar.jpg'
description: # your text below (remove <br> elements if you don't need line breaks)
  A home page to expand on my data analysis projects. All source code can be found on my GitHub profile!
  <br><br>
  <a href="http://www.linkedin.com/in/harrykim1">View LinkedIn Profile</a>   
  
theme: jekyll-theme-minimal
classes: wide
