theme: jekyll-theme-minimal
title: Harry Kim
description: HR Services Analyst in Oracle
logo: https://media-exp1.licdn.com/dms/image/C5603AQHy1PqDZPQtaQ/profile-displayphoto-shrink_400_400/0/1621864730540?e=1648684800&v=beta&t=VmVWgH7mbft0HMBtmDC_nSCA0lN9SfdPI3XRiUn241Q
show_downloads: false
